services:
  - name: tena-api
    type: web
    env: python 
    rootDir: backend
    runtime: python-3.10.13
    buildCommand: |
      pip install -r requirements.txt
      python -m flask db upgrade
    startCommand: gunicorn --bind 0.0.0.0:5000 --worker-class gthread -w 2 --threads 4 run:app
    envVars: 
      - key: FLASK_APP
        value: run.py
    autoDeploy: true