"""Add password reset token fields to User model

Revision ID: 9bd6934af951
Revises: bfbc2d64cd35
Create Date: 2025-11-29 08:43:18.652972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd6934af951'
down_revision = 'bfbc2d64cd35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiration')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
